# Use official Python image, based on Debian latest
FROM python:3.13

WORKDIR /macd_param_analysis

# Copy and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
